### ISSUE TITLE
Shift key is not always typed

### ISSUE THREAD

**Issue by Herrysol** [TabbycatPie/CustomKeyboard#10]
Hello,
I've download the zip archive this morning from the website.
I've created a key map: 
(LShift + S) + (a)
then I connect via RDP session to a Windows 2016 server and open the notepad.
When I press the key and instead of having "Sa" I get "sa". No caps lock enabled.
If I press the key many times in a row, sometimes I get "Sa".

Suggestions?

**Comment by TabbycatPie** [comment]
Maybe network issue? I will test it on my enviroment later.

**Comment by Herrysol** [comment]
Today it stop working correctly also on "normal" Windows. Some macro chars are not running. For example I download on the keyboard "vy.od80e" and the dot char does not appear on notepad.

**Comment by TabbycatPie** [comment]
Is the dot keypad key?(if it is, check the numlock is enabled,you can not type a keypad dot without numlock enabled), and u can also redownload the new version software built from Version3.3 branch (maybe there were some issue which may send wrong hex codes to computer).

**Comment by TabbycatPie** [comment]
Is the dot key a keypad key? if it is, check your numlock, you can not type a keypad dot without numlock enabled.
You can also download the newest version software(maybe there were some issue with old version software causing your device sending wrong hex codes to your computer)
