### ISSUE TITLE
Keys F13-F24, Calculator Have No Output after being assigned

### ISSUE THREAD

**Issue by EmpressSC2** [TabbycatPie/CustomKeyboard#11]
All of the F13-24 keys and Calculator report as being successfully mapped, but they do not output to my device.

I had intended to use the device to set the keys to these kinds of buttons and adjust their function in registry with SharpKeys, but without the usage of these scan codes as I had seen, this software/device adds very little additional functionality :/

Is there some user-end error I could be making that is causing the software to not be able to implement these keys or are they known to be non-functional? If they are known to be, is there any intention to make them work in the near future?

**Comment by TabbycatPie** [comment]
This was a bug in old version firmware which be fixed recently. Im sorry to make this happen, maybe you should to buy a device with new version firmware,sorry QAQ

**Comment by EmpressSC2** [comment]
Ah thanks for getting back, so there's nothing  I can do for my current device? I'll probably just return it in that case but how can I be sure the next one will not have the same issue?

**Comment by TabbycatPie** [comment]
I think maybe you can give your feedback to the customer service of where you bought that device. They will handle this.

**Comment by sjain882** [comment]
Just to confirm does this one support F13-F24? And can I bind it using this software?
https://www.ebay.co.uk/itm/125193951782
Edit: confirmed as working on 2 key 3d printed base micro usb version. works as per readme of this github.
