### ISSUE TITLE
Generate key press sequence

### ISSUE THREAD

**Issue by InI4** [TabbycatPie/CustomKeyboard#12]
I want to create for example a Thor-Rune (þ), i.e. Alt-0254, meaning, Alt is pressed and while it is kept pressed the digits 0254 are pressed in order. I do not manage to do this with the tool. What am I missing?

- First problem of this virtual mouse keyboard is, that I can only press one thing at once.
- Wouldn't it be easier if I could type these description strings in a config file and simply upload them to the device.
- I.e. instead of constructing (LAlt + 0) + (2) + (5) + (4) I would need something like (LAlt + (0)+(2)+(5)+(4)) or similar.
- I hoped I could do it with the ADD feature, but the righthand button is only either DELETE or ADD.

If I do not get this to work, the keyboard is pretty useless for me.

**Comment by TabbycatPie** [comment]
1.the keyboard only support multiple normal keys pressed at once(and only 6 keys maximum) ,I think u maybe meaning something like (LAlt + 0) + (LAlt +2) +(LAlt + 5) + (LAlt + 4)  ,that means press 0 while LAlt is pressing and then release them, then press 2 with holding LAlt and ....
2.I will consider make that next version
3.if you want pressing the 5 keys at the same time, sorry, this keyboard does not have this feature.
4.yes,the ADD feature is only for usecase like making a key act like 'LAlt','LShift'... or a macro contains **clicking**(press and release) a 'LAlt','LShift'...
* pressing muiltiple normal keys at once or making them in a macro is not  allowed on the device, that is a very rare usecase I encountered. Sorry again.

**Comment by InI4** [comment]
Thx for your reply. I'll keep my device and hope for the new version. I am not sure, if that does what I want to (generate obscure strange characters, I use too often).
