### ISSUE TITLE
Firmware does not support remote wake

### ISSUE THREAD

**Issue by nhamer** [TabbycatPie/CustomKeyboard#14]
It would be really nice if this firmware could support USB remote wake signalling 

Some implementation notes based on the microchip stack here: https://www.microchip.com/forums/FindPost/929353

**Comment by TabbycatPie** [comment]
I dont know which version you bought but it is already support by newer firmware. The remote wake signaling is supported by HID protocol, you can see the codes in usb.c there are some arraies for configuring keyboard wake up.

**Comment by nhamer** [comment]
My apologies, don't know how I missed that. Thanks!
