### ISSUE TITLE
Macro Loop

### ISSUE THREAD

**Issue by zarnas168** [TabbycatPie/CustomKeyboard#16]
Hello! Can you please add the function for Looping macros? Pressing it enough times does not apply.

**Comment by TabbycatPie** [comment]
If you keep pressing a macro button, the device will keep sending keys you set in your macro, what do you mean looping macros?

**Comment by zarnas168** [comment]
So that it would repeat to press the buttons for ever on a loop. For example to be able to set macros that would press buttons for 12 hours straight or something like this.

**Comment by TabbycatPie** [comment]
Well, I mean do not release the button ,maybe you can put something a little bit heavy on that macro button, or use some tape to make that happen. But this device can not setting up a macro that do not release some keys(like keep pressing 'w' for going straight in some games)

**Comment by captainwasabi** [comment]
To do this you could have it trigger an autohotkey macro which does have looping capability.
