### ISSUE TITLE
configuration from the CLI?

### ISSUE THREAD

**Issue by captainwasabi** [TabbycatPie/CustomKeyboard#20]
I'd like to be able to do something like this to load/push a config to the device:

`CustomKeyboard  -d d:\path\to\config.xml`

-d : Download it to the device and dont' bring up the interface.

if there is no -d then just load it into the interface

This would let me easily write a little program that would change the mapping based on the application that is in the foreground. Or a little tray popup that would let me pick from a list. or a bunch of things.  I think it would be really useful.

**Comment by TabbycatPie** [comment]
there is no cli, only gui. sorry.
