### ISSUE TITLE
Vulnerabilities? 

### ISSUE THREAD

**Issue by Lukyprod** [TabbycatPie/CustomKeyboard#23]
Hi,

I'd like to know if there are any vulnerabilities in the application.

Thank you.

**Comment by TabbycatPie** [comment]
Hi，this keyboard is based on defualt hid driver，and the hardware itself does not rely on any internet servises ，so I dont think there will be any chance to contrl your hardware remotely. You can use the host software in a virtual envirment to change config for safety.Thank you.Sent from my iPhoneOn Sep 4, 2024, at 15:29, Lukyprod ***@***.***> wrote:﻿
Hi,
I'd like to use it at work but I need to know if there are any vulnerabilities in the application.
Thank you.
